/**
   * Задаёт допустимые значения для AuditAction, используемые в типизированных проверках и обмене данными.
   */
export enum AuditAction {
  AUTH_LOGIN = 'AUTH_LOGIN',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_CONFIRMED = 'USER_CONFIRMED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_RESTORED = 'USER_RESTORED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  CATALOG_CREATED = 'CATALOG_CREATED',
  CATALOG_UPDATED = 'CATALOG_UPDATED',
  CATALOG_DELETED = 'CATALOG_DELETED',
  CATALOG_RESTORED = 'CATALOG_RESTORED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_COURIER_ASSIGNED = 'ORDER_COURIER_ASSIGNED',
  ORDER_ITEM_CHANGED = 'ORDER_ITEM_CHANGED',
  KNOWLEDGE_UPLOADED = 'KNOWLEDGE_UPLOADED',
  CHAT_QUERY = 'CHAT_QUERY',
  ACCESS_DENIED = 'ACCESS_DENIED',
  RATE_LIMITED = 'RATE_LIMITED',
}

/**
   * Задаёт допустимые значения для AuditResult, используемые в типизированных проверках и обмене данными.
   */
export enum AuditResult {
  SUCCESS = 'SUCCESS',
  DENIED = 'DENIED',
  FAILED = 'FAILED',
}
