export enum Status {
  NEW = 'NEW',
  CREATED = 'CREATED',
  ACCEPTED = 'ACCEPTED',
  COOKING = 'COOKING',
  READY = 'READY',
  DELIVERING = 'DELIVERING',
  COMPLETED = 'COMPLETED',
  CANCELLED_CUSTOMER = 'CANCELLED_CUSTOMER',
  CANCELLED_COURIER = 'CANCELLED_COURIER',
}