export enum Status {
  NEW = 'NEW',
  ACCEPTED = 'ACCEPTED',
  COOKING = 'COOKING',
  READY = 'READY',
  DELIVERING = 'DELIVERING',
  COMPLETED = 'COMPLETED',
  CANCELLED_CUSTOMER = 'CANCELLED_CUSTOMER',
  CANCELLED_COURIER = 'CANCELLED_COURIER',
  CANCELLED_STAFF = 'CANCELLED_STAFF',
}

export const CANCELLED_STATUSES: Status[] = [
  Status.CANCELLED_CUSTOMER,
  Status.CANCELLED_COURIER,
  Status.CANCELLED_STAFF,
];


export const CLOSED_STATUSES: Status[] = [
  Status.COMPLETED,
  ...CANCELLED_STATUSES,
];
